# Base16 Chalk
# Scheme: Chris Kempson (http://chriskempson.com)
# foreground=#d0d0d0
# background=#151515
# cursor=#d0d0d0
#
# color0=#151515
# color1=#fb9fb1
# color2=#acc267
# color3=#ddb26f
# color4=#6fc2ef
# color5=#e1a3ee
# color6=#12cfc0
# color7=#d0d0d0
# color8=#505050
# color9=#fb9fb1
# color10=#acc267
# color11=#ddb26f
# color12=#6fc2ef
# color13=#e1a3ee
# color14=#12cfc0
# color15=#f5f5f5
#
# color16=#eda987
# color17=#deaf8f
# color18=#202020
# color19=#303030
# color20=#b0b0b0
# color21=#e0e0e0
#
# Colors are specified using their hexadecimal values with a # prefix: #RRGGBB.

[colors]
# When true, bold text is drawn using the bright color variants(default=false).
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = "#151515"
foreground = "#d0d0d0"

# Colors which should be used to draw the terminal cursor.
[colors.cursor]
cursor = "#d0d0d0"

# Colors used for drawing selections.
[colors.selection]
cursor = "#e0e0e0"

# Normal colors
[colors.normal]
black = "#14151b"
red = "#fb9fb1"
green = "#acc267"
yellow = "#ddb26f"
blue = "#6fc2ef"
magenta = "#e1a3ee"
cyan = "#12cfc0"
white = "#d0d0d0"

# Bright colors
[colors.bright]
black = "#505050"
red = "#fb9fb1"
green = "#acc267"
yellow = "#ddb26f"
blue = "#6fc2ef"
magenta = "#e1a3ee"
cyan = "#12cfc0"
white = "#f5f5f5"
